server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#mybatis 映射配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ffw.mybatis.dto
  #配置mybatis方法自动转驼峰
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      example:
        mapper : debug